### ISSUE TITLE
Price displayed incorrectly 

### ISSUE THREAD

**Issue by obender** [Safe-Deal/Extension#14]
![image](https://github.com/user-attachments/assets/c7983d21-de28-4bae-91f1-cd2c03a95625)

**Comment by obender** [comment]
https://www.amazon.com/CPPSLEE-Halloween-Lion-Costume-Brown/dp/B075KPDJ49/


@safiurrehman96 Please fix after zustand 
cc: @ChenReuven

**Comment by safiurrehman96** [comment]
![image](https://github.com/user-attachments/assets/3f4abc70-41ce-4451-a370-b4e1251ec044)

I can't replicate it. The x-axis shows date so I think that it is showing date in milliseconds in the screenshot you have attached. It might be a temporary glitch in the browser. Can you check again?

**Comment by safiurrehman96** [comment]
![image](https://github.com/user-attachments/assets/658f6587-5d39-4556-9c34-b479072cbdb9)

I can't replicate it on my side. X-axis shows date so I think due to some glitch it is showing it in milliseconds. It might be a temporary thing in the browser. Can you check again?
