### ISSUE TITLE
Search Result List Icon not opening baloon on hover

### ISSUE THREAD

**Issue by Carmageddon** [Safe-Deal/Extension#17]
In Amazon, cant review summary
<img width="1840" alt="Screenshot 2024-10-21 at 12 48 01" src="https://github.com/user-attachments/assets/aaf4f92e-0180-46e4-a9a4-01cfd98f4b36">

**Comment by safiurrehman96** [comment]
@Carmageddon On categories or search listing pages extension only shows the badge. Summary is for individual product pages only.

**Comment by Carmageddon** [comment]
@safiurrehman96 It is a defect, it was working before in the past. So this functionality needs to be brought back.
Please also add an jest test to ensure this does not break again.

**Comment by safiurrehman96** [comment]
@Carmageddon Alright.
