### ISSUE TITLE
Coupons page cant be reopened a second time

### ISSUE THREAD

**Issue by Carmageddon** [Safe-Deal/Extension#23]
When you do a search, and get a bunch of coupons listed (when clicking the dollar icon)
<img width="72" alt="image" src="https://github.com/user-attachments/assets/77c22570-6d29-414e-b345-98bed269e4ae">

 - it works the first time, but close the modal, and re-open again - you get the following error:

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/d43e9c48-76c1-4879-bcf1-7ffc7ae0446a">

Trying to reproduce, it can even disappear and go to error mode without closing the modal, happened to me while capturing screenshot of coupons results.

**Comment by safiurrehman96** [comment]
@Carmageddon I haven't been able to reproduce it. Any specific conditions to trigger it?

**Comment by Carmageddon** [comment]
The bug seem to be gone, I don't have the specific listing anymore, next time will record the URL to reproduce as well.
